### PR TITLE
Reading list backend

### LINKED ISSUE #26: Mimic backend logic of bookmark to implement reading list

### PR DESCRIPTION
**Pull request by terryyLi**
Trying to resolve #26 but it still does not work.

### CODE REVIEW

**Review by torqueJY32 — COMMENTED** [review]
It seems that mass testing is not passing through, which might mean there are potential issues in the code. I would suggest we do not change the language json file as suggested in each json file. We can just modify the tpl file to show a default English promot.

**Comment by terryyLi** [comment]
> It seems that mass testing is not passing through, which might mean there are potential issues in the code. I would suggest we do not change the language json file as suggested in each json file. We can just modify the tpl file to show a default English promot.

sure let me revert changes for language files.

**Review by torqueJY32 — COMMENTED** [review]
We should also maybe create a branch in the team repository as it seems to be very difficult to merge at this moment

**Comment by terryyLi** [comment]
> We should also maybe create a branch in the team repository as it seems to be very difficult to merge at this moment

we can close this PR and I'm still working on my branch and open a new PR after fix.

**Pull request closed without merging**
